urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name='phonebook'
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup'),
    path('', views.ContactListView.as_view(), name='contact-index'),
    path('add-contact', views.ContactCreateView.as_view(), name='add-contact'),
    path('<int:pk>/update-contact',views.ContactUpdateView.as_view(),name='update-contact'),
    path('<int:pk>/delete-contact', views.ContactDeleteView.as_view(),name='delete-contact'),
]

models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User


# Create your models here.
class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=45)
    email = models.EmailField()
    telephone = models.CharField(max_length=15)
    relation = models.CharField(max_length=45)
    residence = models.CharField(max_length=45)
    cover = models.FileField()
    is_male = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('phonebook:contact-index')

forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from. models import Contact
from .forms import UserForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ContactListView(LoginRequiredMixin,ListView):
    model = Contact
    context_object_name = 'contacts'

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)

class ContactCreateView(LoginRequiredMixin, CreateView):
    model = Contact
    fields = ['name', 'email', 'telephone', 'relation', 'residence', 'cover', 'is_male']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ContactUpdateView(UpdateView):
    model = Contact
    fields = ['name', 'email', 'telephone', 'relation', 'residence', 'cover', 'is_male']


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = '/'


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('phonebook:contact-index')

    return render(request, 'phonebook/signup.html', {'form': form})

templates/phonebook/base.html
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{% url 'phonebook:contact-index' %">phonebook</a>
    <ul class="navbar-nav mr-auto ml-5">
      <li>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
      </li>
    </ul>
        <ul class="navbar-nav navbar-right">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'phonebook:add-contact' %} "><i class="fas fa-plus">&nbsp;Add contact</i> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'phonebook:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
      </li>
    </ul>
  </div>
</nav>


{%block content %}{% endblock%}
</body>

 </html>

templates/phonebook/contact_confirm_delete.html
{% extends 'phonebook/base.html' %}
{% block title %}Confirm delete{% endblock %}


{%block content%}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-1">
                <h3>Delete contact {{ object.name }}</h3>
                <hr>
                <p>Are you sure you want to delete?</p>
                <form method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-danger">Yes, delete</button>
                        <a href="{% url 'phonebook:contact-index' %}" class="btn btn-outline-secondary"></a>
                    </div>


                </form>
            </div>

        </div>


    </div>


</div>
{% endblock %}

templates/phonebook/contact_form.html
{% extends 'phonebook/base.html' %}
{%block title%}{%if object%}Update{%else%}Add contact {%endif%} {%endblock%}
{%block content%}
{%load crispy_forms_tags%}
<div class="container">
    <div class="'row">
        <div class ='col-sm-3'></div>
        <div class="col-sm-6">
            <div class="card card-body">
                <h4>{% if object%}Update {{ object.name}}{% else%}Add Contact{%endif%}</h4>
                <hr>
                <form class="for-horizontal" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    {{ form|crispy}}
                    <div class="form-group">
                        <button type="submit" class="btn btn-info">{%if object%}Update{%else%} Submit{%endif%}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/phonebook/contact_list.html
{% extends 'phonebook/base.html' %}
{% block title %}Contacts{% endblock %}
{% block content %}
<div class="container">

    <div class="row">
      {% if contacts %}
        {% for contact in contacts %}
            <div class="col-sm-3">
                <div class="card my-1">
                    <img src="{{ contact.cover.url}}" class="img src img-responsive" alt="" style="height :150px;">
                    <div class="car-header" style="background-color: {% if contact.is_male %}blue; {% else %}red;{% endif %}">
                        <i class="fas{% if contact.is_male %}fa-mars{% else %} fa-venus{% endif %}"></i>&nbsp;
                        {{contact.name}}


                    </div>
                    <div class="card-body" style="color: {% if contact.is_male %}blue; {% else %}red; {% endif %}">
                        <p><i class="fas fa-envelope"></i>&nbsp; {{contact.email}}</p>
                        <p><i class="fas fa-telephone"></i>&nbsp; {{contact.telephone}}</p>
                        <p><i class="fas fa-user-circle"></i>&nbsp; {{contact.relation}}</p>
                        <p><i class="fas fa-globe"></i>&nbsp; {{contact.residence}}</p>

                        <a href="{% url 'phonebook:update-contact' contact.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'phonebook:delete-contact' contact.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
      {% endif %}
    </div>>
</div>
{% endblock %}

templates/phonebook/signup.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% load crispy_forms_tags %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body">
                <h3>signup</h3>
                <hr>
                <form method="post"  class="form-horizontal">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group">
                        <button type="submit" class="btn btn-info">signup</button>
                    </div>
                    <p class="text-center">Already registered?<a href="(% url 'phonebook:login' %)">Login</a></p>
                </form>
            </div>
        </div>
    </div>
</div>